db:
  image: mysql:latest
  environment: 
    MYSQL_ROOT_PASSWORD: mysecretpassword 
    MYSQL_DATABASE: production_brimir
  volumes:
    - ./database/mysql:/var/lib/mysql
web:
  build: .
  volumes:
    - ./web:/public/system
  ports:
    - "3000:3000"
  links:
    - db
